#!/bin/bash

# Generate certificate
openssl req -nodes -extensions v3_req -utf8 -newkey rsa:2048 -keyout nick.key -x509 -days 730 -out nick.cer -subj "/C=NO/ST=Hordaland/L=Bergen/O=UiB/OU=IT Department/CN=Ingar Smedstad"
cat nick.cer nick.key > nick.pem
shred -u -z nick.key nick.cer
openssl req -nodes -newkey rsa:2048 -keyout relay.pem -x509 -days 365 -out relay.pem  -subj "/C=NO/ST=Hordaland/L=Bergen/O=UiB/OU=IT Department/CN=Ingar Smedstad"
