#!/bin/bash

alias ll='ls -al'
alias la='ls -A'
alias l='ls -l'

alias ..='cd ..'
alias ...='cd ../..'
alias -='cd -'

alias mkdir='mkdir -pv'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias cal='cal -3'
