#!/bin/bash

mktmplt () {
  #git clone git@git.uib.no:packages/precise/template ${1}
  mkdir ${1}
  cd ${1}
  git init
  cp /disk2/packages/template/* .
  sed -i "s/NAME=/NAME=${1}/g" Makefile
  git add *
  git commit -m"initial release"
  git remote add origin git@git.uib.no:packages/ubuntu/${1}
  git push -u origin master
}

