# Path to your oh-my-zsh configuration.
ZSH=$XDG_CONFIG_HOME/zsh/oh-my-zsh

!!@@theme

ZSH_CUSTOM=$XDG_CONFIG_HOME/zsh/oh-my-zsh-custom

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

plugins=( \
    git \
    gitfast \
    history-substring-search \
    ssh-agent \
    sudo \
    themes \
    tmux \
    tmuxinator \
    vagrant \
    web-search \
    zsh-syntax-highlighting \
    !!@@plugins
)

source $ZSH/oh-my-zsh.sh

zstyle :omz:plugins:ssh-agent agent-forwarding on

# Base config

setopt autocd
setopt noclobber
setopt bashautolist
#unsetopt correct_all
set -o vi
bindkey '^R' history-incremental-search-backward
# bind Up and Down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
# Sudo 
bindkey "^S" sudo-command-line

# Base alias
source "$XDG_CONFIG_HOME/alias/aliases"
alias ssh='TERM=rxvt-unicode ssh'
alias vagrant='TERM=rxvt-unicode vagrant'

autoload bashcompinit
bashcompinit
#source $HOME/.local/lib/dots/contrib/bash_completion
source $HOME/.config/bash/completions.d/*.bash
