#!/bin/bash

!!@@monitors

bspc rule -a \* floating=on
bspc rule -a urxvt floating=off
bspc rule -a Gimp desktop=^8
bspc rule -a Chromium-browser desktop=^2 follow=on
bspc rule -a VirtualBox desktop=^3
bspc rule -a xcalc floating=off pseudo_tiled=on

bspc config border_width        1
bspc config window_gap          10
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 0.1

bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#ffffff"
bspc config urgent_border_color "#191919"

if [ $(pgrep -cx panel) -ge 1 ] ; then
  pkill panel
fi

$XDG_CONFIG_HOME/bspwm/panel/panel &
