local indent = 2
vim.opt.ma = true
vim.opt.mouse = "a"
vim.opt.cursorline = true
vim.opt.termguicolors = true
vim.opt.tabstop = indent
vim.opt.shiftwidth = indent
vim.opt.softtabstop = indent
vim.opt.expandtab = true
vim.opt.autoread = true
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.foldlevelstart = 99
vim.opt.scrolloff = 7
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.swapfile = false
vim.opt.clipboard = "unnamedplus"
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' }
vim.opt.signcolumn = 'yes'
