#!/bin/bash

alias ls='ls --group-directories-first --color=auto -h'
alias ll='ls -al'
alias la='ls -A'
alias l='ls -C'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias pwdb="cd && keepassx -cfg $HOME/.pwdb.ini &"
alias hjemmekontor="rdesktop -g 1024x768 -a 16 -k no -d UiB hjemmekontor.uib.no &"
alias gitls='ssh git@git.uib.no'

