#!/bin/bash

if [ -z $XDG_CONFIG_HOME ]; then
  XDG_CONFIG_HOME=$HOME/.config
fi

# Clone fonts into directory if it is not allready done
if [[ ! -e $XDG_CONFIG_HOME/fonts/README.rst ]]; then
  echo -e "\033[0;32m==>\033[0m Installing fonts..."
  rm -rf * .* > /dev/null 2>&1
  git clone --quiet https://github.com/Lokaltog/powerline-fonts .
  rm -f $HOME/.fonts > /dev/null 2>&1
  ln -s $XDG_CONFIG_HOME/fonts $HOME/.fonts
  fc-cache
fi
